### ISSUE TITLE
你好 作者大大

### ISSUE THREAD

**Issue by HowlJo** [great-jin/elderly-healthcare#1]
在研究这个项目，感觉部门在前台写死的吗 是否可以补充一下sql表记录 学习下

**Comment by great-jin** [comment]
很抱歉我现在也没有保存当时的测试数据，回顾了一下代码部门信息应该读取organize_info表中的字典信息，具体值应该是staffManage/index.vue 中树组件的title值，你可以根据需要自定义修改数据，职位信息则是写死在前台页面固定值，如有需要可根据部门信息获取同理修改。
